[package]
name = "liblspc"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-types = "0.97.0"
parking_lot = "0.12.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.120", features = ["raw_value"] }
tokio = { version = "1.38.1", features = ["full"] }
